import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import CssBaseline from "@mui/material/CssBaseline";
import ScopedCssBaseline from "@mui/material/ScopedCssBaseline";
import * as React from "react";
import { LayoutProps } from "@/interfaces/layout_props";

export const metadata: Metadata = {
  title: "Hello Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <body>
        <React.Fragment>
          <ScopedCssBaseline />
          {props.children}
        </React.Fragment>
      </body>
    </html>
  );
}
