FROM python:3.12.1-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app/

COPY requirements.txt ./app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r ./app/requirements.txt



RUN mkdir -p /var/www/static

VOLUME /var/www/static
VOLUME /app/nginx/conf.d

RUN python manage.py collectstatic --noinput

CMD python manage.py migrate && gunicorn --bind 0.0.0.0:8000 core.wsgi:application