FROM python:3.12.1-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app/

COPY requirements.txt ./app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r ./app/requirements.txt

RUN mkdir -p /var/www/static

VOLUME /var/www/static
VOLUME /app/core/media

RUN python manage.py collectstatic --noinput

COPY python_entrypoint.sh /app/python_entrypoint.sh
RUN chmod +x /app/python_entrypoint.sh
ENTRYPOINT ["/app/python_entrypoint.sh"]
