# Generated by Django 5.0.4 on 2024-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification')], max_length=32),
        ),
    ]
