# Generated by Django 5.0.4 on 2024-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_verificationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
