# Generated by Django 4.2.4 on 2023-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=190, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=190, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=190, verbose_name='profile_photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_summary',
            field=models.TextField(blank=True, verbose_name='profile_summary'),
        ),
    ]
