# Generated by Django 4.2.4 on 2023-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo.png',
            field=models.ImageField(blank=True, height_field='180', upload_to='core/media/profile_photos', width_field='180'),
        ),
    ]
