# Generated by Django 4.2.4 on 2023-10-10 07:49

from dashboard.models.user import rename_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="height_field",
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name="user",
            name="width_field",
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                height_field="height_field",
                null=True,
                upload_to=rename_file,
                width_field="width_field",
            ),
        ),
    ]
