# Generated by Django 4.2.4 on 2023-11-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner_closed',
        ),
        migrations.AddField(
            model_name='event',
            name='closed_dates',
            field=models.BooleanField(default=False, verbose_name='closed_dates'),
        ),
    ]
