# Generated by Django 4.2.4 on 2023-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('1', 'public'), ('2', 'non-business-hours'), ('3', 'unavailable')], default='1', max_length=2),
        ),
    ]
