# Generated by Django 4.2.4 on 2023-11-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.event')),
            ],
            bases=('dashboard.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Non Business Hours'), ('3', 'Unavailable')], default='1', max_length=2),
        ),
    ]
