# Generated by Django 4.2.4 on 2023-12-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_user_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name='public_id'),
        ),
    ]
