# Generated by Django 4.2.4 on 2024-01-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_event_end_recur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_recur',
            field=models.DateField(blank=True, null=True, verbose_name='end_recur'),
        ),
    ]
