# Generated by Django 4.2.4 on 2024-04-01 06:50

from dashboard.models.user import CustomUserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_alter_event_end_recur"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", CustomUserManager()),
            ],
        ),
    ]
