# Generated by Django 5.0.8 on 2024-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(blank=True, default=180, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(blank=True, default=180, null=True),
        ),
    ]
