# Generated by Django 5.0.4 on 2024-07-04 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_verificationtoken_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
