# Generated by Django 5.0.8 on 2024-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_verificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('forgot_password_verification', 'Forgot Password Verification')], max_length=32),
        ),
    ]
