# Generated by Django 5.1.14 on 2026-08-03 19:02
#
# `AlterModelTable` also cascades to rename the two auto-generated M2M through-tables
# (dashboard_user_groups/dashboard_user_user_permissions -> identity_user_*) — confirmed via
# `sqlmigrate`, no manual SQL needed for that.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_verificationtoken_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
