FROM node:22-alpine as builder

WORKDIR /app

RUN mkdir -p /usr/local/bin

COPY ./src/frontend ./
COPY ./.shell/node_entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/node_entrypoint.sh

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED 1

USER node


ENTRYPOINT [ "/bin/sh", "/usr/local/bin/node_entrypoint.sh"]