FROM python:3.12.1-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY src/api /app/

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt

RUN mkdir -p /var/www/static

VOLUME /var/www/static
VOLUME /app/core/media

RUN chmod +x /app/.shell/python_entrypoint.sh
ENTRYPOINT ["/app/.shell/python_entrypoint.sh"]
