# Generated by Django 5.1.14 on 2026-09-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Legacy EventTypes values (event/enums.py) — hardcoded here rather than imported since
# migrations must not depend on app code that can change out from under them.
_LEGACY_BUSINESS_HOURS = "2"
_LEGACY_UNAVAILABLE = "3"


def _week_day_indices(event):
    """Sunday=0..Saturday=6, matching RecurrenceTypes. A blank frequency means a single
    occurrence — derive the day from start_date instead of a recurrence list."""
    if event.frequency:
        return [int(day) for day in event.frequency.split(",") if day != ""]
    return [(event.start_date.weekday() + 1) % 7]


def migrate_legacy_business_hours_and_unavailable(apps, schema_editor):
    Event = apps.get_model("event", "Event")
    Schedule = apps.get_model("event", "Schedule")
    ScheduleWeeklyHours = apps.get_model("event", "ScheduleWeeklyHours")
    ScheduleOverride = apps.get_model("event", "ScheduleOverride")

    schedules_by_user_id = {}

    def schedule_for(event):
        schedule = schedules_by_user_id.get(event.user_id)
        if schedule is None:
            schedule, _ = Schedule.objects.get_or_create(
                user_id=event.user_id,
                is_default=True,
                defaults={"name": "Working Hours", "timezone": event.timezone or "UTC"},
            )
            schedules_by_user_id[event.user_id] = schedule
        return schedule

    for event in Event.objects.filter(type=_LEGACY_BUSINESS_HOURS).order_by(
        "user_id", "created_at"
    ):
        schedule = schedule_for(event)
        for day_of_week in _week_day_indices(event):
            ScheduleWeeklyHours.objects.get_or_create(
                schedule=schedule,
                day_of_week=day_of_week,
                start_time=event.start_time,
                end_time=event.end_time,
            )

    for event in Event.objects.filter(type=_LEGACY_UNAVAILABLE).order_by(
        "user_id", "created_at"
    ):
        schedule = schedule_for(event)
        ScheduleOverride.objects.get_or_create(
            schedule=schedule,
            date=event.start_date,
            defaults={"is_unavailable": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Working Hours', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBookingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_notice_minutes', models.IntegerField(default=120)),
                ('max_booking_days', models.IntegerField(default=60)),
                ('buffer_before_minutes', models.IntegerField(default=0)),
                ('buffer_after_minutes', models.IntegerField(default=0)),
                ('daily_booking_limit', models.IntegerField(blank=True, null=True)),
                ('allow_multiple_per_slot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rules', to='event.schedule')),
            ],
            options={
                'db_table': 'event_schedule_booking_rules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleWeeklyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_hours', to='event.schedule')),
            ],
            options={
                'db_table': 'event_schedule_weekly_hours',
            },
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_unavailable', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='event.schedule')),
            ],
            options={
                'db_table': 'event_schedule_overrides',
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.RunPython(
            migrate_legacy_business_hours_and_unavailable,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
