# Generated by Django 4.2.4 on 2023-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=190, verbose_name='profile_photo'),
        ),
    ]
