# Generated by Django 4.2.4 on 2023-10-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_user_profile_photo_user_profile_photo_png'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo.png',
            new_name='profile_photo',
        ),
    ]
