# Generated by Django 4.2.4 on 2023-11-16 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_user_height_field_user_width_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_date', models.DateField(blank=True, verbose_name='end_date')),
                ('end_time', models.TimeField(blank=True, verbose_name='end_time')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='frequency')),
                ('owner_closed', models.BooleanField(default=False, verbose_name='owner_closed')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='note')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='timezone')),
                ('attendees', models.TextField(blank=True, verbose_name='attendee_emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
