# Generated by Django 4.2.4 on 2023-11-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_event_owner_closed_event_closed_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='closed_dates',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[('1', 'PUBLIC'), ('2', 'non-business-hours'), ('3', 'unavailable')], default='1', max_length=2),
        ),
    ]
