# Generated by Django 4.2.4 on 2023-12-26 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_recur',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='end_recur'),
            preserve_default=False,
        ),
    ]
