# Generated by Django 5.0.4 on 2024-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='dashboard.models.user.rename_file', width_field='width_field'),
        ),
    ]
