# Generated by Django 5.0.4 on 2024-06-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_alter_user_profile_photo"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS dashboard_eventservice;",
            reverse_sql="CREATE TABLE dashboard_eventservice (event_ptr_id UUID PRIMARY KEY);",
        ),
    ]
