# Generated by Django 5.1.14 on 2026-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
