from .profile_update_view import ProfileUpdateView
from .password_update_view import PasswordUpdateView
from .schedule_manager_view import ScheduleManagerView
from .event_list_view import EventListView
from .event_delete_view import EventDeleteView
from .event_list_business_hours_view import EventListBusinessHoursView
from .event_delete_business_hours_view import EventDeleteBusinessHoursView
from dashboard.views_legacy import *
