name: Metton Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  app-deployment:
    name: Metton Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Change to the root directory
        run: cd ${{ github.workspace }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Start containers
        run: docker-compose up --build -d

      - name: Check All Container status
        run: docker ps -a

      - name: Stop containers
        run: docker-compose down -v

      # - name: Mask AWS ID
      #   run: echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"
        env:
          AWS_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Deploy to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: mettonapp
          IMAGE_TAG: latest
        run: |
          services=$(docker-compose config --services)
          for service in $services; do
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$service-$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$service-$IMAGE_TAG
          done
